name: Deploy to DigitalOcean Server

on:
  push:
    branches:
      - main  # Trigger the action when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v2

      - name: Install SSH key and connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/statsdrone-studio
            git pull origin main
            npm install --production
            pm2 restart strapi

